// Generated by gencpp from file qb_device_msgs/ResourceData.msg
// DO NOT EDIT!


#ifndef QB_DEVICE_MSGS_MESSAGE_RESOURCEDATA_H
#define QB_DEVICE_MSGS_MESSAGE_RESOURCEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qb_device_msgs
{
template <class ContainerAllocator>
struct ResourceData_
{
  typedef ResourceData_<ContainerAllocator> Type;

  ResourceData_()
    : name()
    , position(0.0)
    , velocity(0.0)
    , effort(0.0)
    , command(0.0)  {
    }
  ResourceData_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , position(0.0)
    , velocity(0.0)
    , effort(0.0)
    , command(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _position_type;
  _position_type position;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _effort_type;
  _effort_type effort;

   typedef double _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::qb_device_msgs::ResourceData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qb_device_msgs::ResourceData_<ContainerAllocator> const> ConstPtr;

}; // struct ResourceData_

typedef ::qb_device_msgs::ResourceData_<std::allocator<void> > ResourceData;

typedef boost::shared_ptr< ::qb_device_msgs::ResourceData > ResourceDataPtr;
typedef boost::shared_ptr< ::qb_device_msgs::ResourceData const> ResourceDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qb_device_msgs::ResourceData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qb_device_msgs::ResourceData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace qb_device_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'qb_device_msgs': ['/home/iclab/softhand_ros/src/qbdevice-ros/qb_device_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qb_device_msgs::ResourceData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qb_device_msgs::ResourceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qb_device_msgs::ResourceData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "378205f324e9e9cea98488f8746f3449";
  }

  static const char* value(const ::qb_device_msgs::ResourceData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x378205f324e9e9ceULL;
  static const uint64_t static_value2 = 0xa98488f8746f3449ULL;
};

template<class ContainerAllocator>
struct DataType< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qb_device_msgs/ResourceData";
  }

  static const char* value(const ::qb_device_msgs::ResourceData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Device-independent resource data message\n\
\n\
string name\n\
float64 position\n\
float64 velocity\n\
float64 effort\n\
float64 command\n\
";
  }

  static const char* value(const ::qb_device_msgs::ResourceData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.effort);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResourceData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qb_device_msgs::ResourceData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qb_device_msgs::ResourceData_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "effort: ";
    Printer<double>::stream(s, indent + "  ", v.effort);
    s << indent << "command: ";
    Printer<double>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QB_DEVICE_MSGS_MESSAGE_RESOURCEDATA_H
